name: go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.12', '1.13', '1.14']
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: checkout
        uses: actions/checkout@v2

      - name: tools
        run: go get golang.org/x/lint/golint

      - name: test
        run: make

